"""
pages/4_Quality_Assistant.py
=============================
RAG-based Quality Assistant ("Track 3 — RAG for Industrial Knowledge
Management"). Lets an operator ask natural-language questions about defect
causes, corrective actions, the ISO 23247 mapping, and quality standards.
Answers are grounded in (and cite) a small SOP knowledge base.
"""

from pathlib import Path
import sys

import streamlit as st

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from core.rag import compose_local_answer, generate_answer, get_knowledge_base  # noqa: E402

st.set_page_config(page_title="Quality Assistant — Checkered Fabric AOI", page_icon="💬", layout="wide")

st.title("💬 Quality Assistant")
st.caption("RAG over a 12-document SOP / standards knowledge base — User Entity (ISO 23247)")

kb = get_knowledge_base()

import core.rag as ragmod
has_claude = ragmod._get_api_key() is not None
if has_claude:
    st.success("Claude API key detected — answers are generated by Claude, grounded in retrieved sources.", icon="🤖")
else:
    st.info(
        "No Claude API key found — answers are composed locally (extractive) "
        "from the retrieved documents. Set ANTHROPIC_API_KEY (env var or "
        ".streamlit/secrets.toml) to upgrade to LLM-generated answers.",
        icon="ℹ️",
    )

EXAMPLES = [
    "What causes a Circle defect and how do I fix it?",
    "Why might a Line defect be confused with no defect?",
    "What is the OME in this digital twin?",
    "How does the AOI station need to be maintained?",
    "How accurate is the model and what are its limitations?",
]

st.markdown("**Try an example:**")
cols = st.columns(len(EXAMPLES))
clicked = None
for col, ex in zip(cols, EXAMPLES):
    if col.button(ex, use_container_width=True):
        clicked = ex

if "qa_history" not in st.session_state:
    st.session_state.qa_history = []

query = st.chat_input("Ask the Quality Assistant...") or clicked

if query:
    results = kb.retrieve(query, top_k=3)
    answer = None
    if has_claude:
        answer = generate_answer(query, [d["content"] for _, d in results])
    if answer is None:
        answer = compose_local_answer(query, results, kb)
    st.session_state.qa_history.append((query, answer, results))

for query, answer, results in reversed(st.session_state.qa_history):
    with st.chat_message("user"):
        st.markdown(query)
    with st.chat_message("assistant"):
        st.markdown(answer)
        with st.expander(f"Sources ({len(results)})"):
            for score, doc in results:
                st.markdown(f"**{doc['title']}** — relevance {score:.2f}")
                st.caption(doc["content"].strip()[:300] + "...")

if not st.session_state.qa_history:
    st.markdown("---")
    with st.expander("📚 Knowledge base contents (12 documents)"):
        for doc in kb._docs:
            st.markdown(f"- **{doc['title']}**")
